#############################################################################
# This config file is a necessary input file for the cactus GPU snakemake
# pipeline. 
#
# Before using this config file, first run cactus-prepare:
# <cactus_path> cactus-prepare <input_file> --outDir <output_dir> --jobStore <tmp_dir> --gpu
#
# Then replace the values below with the same paths in the fields below
# e.g.: 
# input_file: <input_file>
# input_file: /path/to/my/input/file.txt
#
# For working_dir, I prefer to make this one directory above my output_dir
#
# Gregg Thomas, Spring 2022
#############################################################################

working_dir: <working_directory>

cactus_path: <cactus_path>

input_file: <input_file>

output_dir: <output_dir>

tmp_dir: <tmp_dir>

#############################################################################