from glob import glob
from os.path import basename
import yaml
from os import system

configfile: "config/config.yaml"
res_config = yaml.load(open("config/resources.yaml"),Loader=yaml.FullLoader)

###
system("rm gtflist.txt")
   
SAMPLES = list(set([basename(i.split('/')[-1].split('_')[1]) for i in glob("%s*bam" % config["bamDir"])]))

for sample in SAMPLES:
   system("echo %s%s_stringtie_%s.gtf >> gtflist.txt" % (config["assemblyDir"],sample,config["alignment_tool"]))

system("cat gtflist.txt")

### RULES ###

rule all:
    input:
        config["mergeDir"] + config["mergeLabel"] + "_stringtie-merge_" + config["alignment_tool"] + ".gtf"	

include: "rules/stringtie.smk"
