## ALL OF BELOW NEED TO BE MODIFIED TO WORK
## FOR YOUR DATA!!

# LABEL FOR MERGED ASSEMBLIES #
speciesname: "human"

########################
## RNA-SEQ FASTQ FILES #
########################
# fastq input file data ##
# Illumina short reads #

fastqDir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/fastq/human/trimmed_reads/"

# long reads #
longreadsDir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/LongReadTesting/human/pacbio/reads/"
longreads_file_extension: "fastq"
# genome #
genome: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/genomes/human/headcleaned_GCF_000001405.39_GRCh38.p13_genomic.fna"

############
## HISAT2 ##
############
Hisat2IndexDir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/genomes/human/hisat2/" 
Hisat2IndexPrefix: "GCF_000001405.39_GRCh38.p13" 
Hisat2Outdir: "results/hisat2/"
Hisat2SamsortOutdir: "results/hisat2/bams/" 

##########
## STAR ##
#########
#StarIndexDir: 
#StarOutDir: "results/star/"
#Star1stPassOutdir: "results/star/star1stpass/" 
#Star2ndPassOutdir: "results/star/star2ndpass/"
#StarSamsortOutdir: "results/star/bams/" 

##############
## Minimap2 ##
##############
Minimap2IndexDir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/LongReadTesting/human/pacbio/minimap2_index/"
minimap2_index_datatype: "Iso-seq"
minimap2_outdir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/LongReadTesting/human/pacbio/minimap2_alignments/"
minimap2SamsortOutdir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/LongReadTesting/human/pacbio/minimap2_alignments/bams/"

#############
# STRINGTIE #
# ###########
# Hisat2#
StringtieHisat2AssemblyDir: "results/stringtie/hisat2/individual_assemblies/" 
StringtieHisat2MergeDir: "results/stringtie/hisat2/merged_assembly/" 
# STAR #
StringtieStarAssemblyDir: "results/stringtie/star/individual_assemblies/"
StringtieStarMergeDir: "results/stringtie/star/merged_assembly/"

# Minimap2/Long Reads #
StringtieLongReadsAssemblyDir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/LongReadTesting/human/pacbio/stringtie/inidividual_assemblies/"
StringtieLongReadsMergeDir: "/n/holylfs05/LABS/informatics/Lab/genome_annotation_project/mammals/LongReadTesting/human/pacbio/stringtie/mergedassembly/"
##############
##  SCALLOP ##
#############
#ScallopHisat2Dir: "results/scallop/hisat2/"
#ScallopHisat2AssemblyDir: "results/scallop/hisat2/individual_assemblies/" 
#TacoHisat2Dir: "results/scallop/hisat2/taco/"
#ScallopStarDir: "results/scallop/star/"
#ScallopStarAssemblyDir: "results/scallop/star/individual_assemblies/"
#TacoStarDir: "results/scallop/star/taco/" 
