---
  title: "Genome Annotation Project"
subtitle: "Figure 2: CDS count ratio vs. length ratio (relative to NCBI): 
date: "December 13, 2024"
author: "Adam Freedman"
output: 
  html_document: default
---
  
## Set up
```{r,,message=FALSE, warning=FALSE}
currentdir=getwd()
setwd(currentdir)
library(tidyverse)
``` 

## Data
```{r,,message=FALSE, warning=FALSE}
annotations <-read_csv("../../data/Table_S3.csv")
annotations <- annotations %>% filter(!method %in% c("BrkProt-unfilt","BrkProt-fullsupport","BrkRNA-unfilt",
                                                     "BrkRNA-fullsupport","CGPdenovo","TSEBRA","MakerNoRnaNoEvm",
                                                     "MakerRnaEvm","MakerNoRnaEvm")) 

methodlabels<-c("BRAKER2 (P)","BRAKER1 (P)","BRAKER3 (P)",expression(paste(CGP[protein]," (P)")),expression(paste(CGP[RNA]," (P)")),expression(Scallop[HISAT2]),expression(Scallop[STAR]),expression(Stringtie[HISAT2]),expression(Stringtie[STAR]),"MAKER (P)","TOGA (P)","Liftoff")

annotations$method <- factor(annotations$method,levels=c("BrkProt","BrkRNA","Braker3","CGPprotein","CGPrnaseq",
                                           "ScalHisat","ScalStar","StrHisat","StrStar","MakerRnaNoEvm","TOGA","liftoff"))

annotations <- annotations %>% mutate(species = str_replace(species, "dmelanogaster", "D. melanogaster")) %>%
     mutate(species = str_replace(species, "dpseudoobscura", "D. pseudoobscura")) %>%  
     mutate(species = str_replace(species, "dyakuba", "D. yakuba")) %>%
     mutate(species = str_replace(species, "alyrata", "A. lyrata")) %>%
     mutate(species = str_replace(species, "athaliana", "A. thaliana")) %>%
     mutate(species = str_replace(species, "boleracea", "B. oleracea")) %>%
     mutate(species = str_replace(species, "crubella", "C. rubella")) %>%
     mutate(species = str_replace(species, "osativa", "O. sativa")) %>%
     mutate(species = str_replace(species, "sitalica", "S. italica")) %>%
     mutate(species = str_replace(species, "bdistachyon", "B. distachyon")) %>%
     mutate(species = str_replace(species, "zmays", "Z. mays")) %>%
     mutate(species = str_replace(species, "bmori", "B. mori")) %>%
     mutate(species = str_replace(species, "herato", "H. erato")) %>%
     mutate(species = str_replace(species, "dplexippus", "D. plexippus")) %>%
     mutate(species = str_replace(species, "human", "H. sapiens")) %>%
     mutate(species = str_replace(species, "macaque", "M. mulatta")) %>%
     mutate(species = str_replace(species, "dog", "C. familiaris")) %>%
     mutate(species = str_replace(species, "mouse", "M. musculus")) %>%
     mutate(species = str_replace(species, "chicken", "G. gallus")) %>%
     mutate(species = str_replace(species, "quail", "C. japonica")) %>%
     mutate(species = str_replace(species, "mallard", "A. platyrhynchos"))


annotations <- annotations %>% mutate_at(vars(species),factor,levels=c("D. melanogaster",
              "D. yakuba", "D. pseudoobscura","A. thaliana", "A. lyrata","C. rubella","B. oleracea","Z. mays","S. italica","O. sativa",
               "B. distachyon", "G. gallus","C. japonica","A. platyrhynchos","H. sapiens","M. mulatta","M. musculus","C. familiaris","H. erato","D. plexippus","B. mori"))
```


## Figure 2
```{r}
refratio_biplot<- annotations %>% filter(species %in% c("H. sapiens","G. gallus","A. thaliana","D. melanogaster","Z. mays","M. musculus")) %>% ggplot() + 
     geom_point(mapping=aes(y=log10(number_CDS/protcod_mRNA_NCBI),x=MedianCDSLength/RefMedianCDSLength,color=method,shape=species),alpha=0.7,size=3.5) +
    ylab(expression(paste(log[10],"(# predicted CDS/# NCBI CDS)"))) +
    xlab("Median CDS length/median NCBI CDS length")  + 
    scale_color_manual(labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen")) +
     scale_shape_manual(values=c(0,1,15,2,16,17)) +
     theme(axis.title=element_text(size=12),legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm")) + 
    guides(color = guide_legend(title = "Method",override.aes = list(shape=15),order=1,label.theme = element_text(angle = 0, size=10,face = "plain"))) +
    guides(shape = guide_legend(title = "Species",order=2,label.theme = element_text(angle = 0, size=10,face = "italic"))) +
  geom_vline(xintercept=1,linetype="dotted",size=1,color="black") +
  geom_hline(yintercept=0,linetype="dotted",size=1,color="black")
  

print(refratio_biplot)
ggsave(refratio_biplot,file="Figure2.pdf",width=6,height=5) 
```
