---
  title: "Genome Annotation Project"
subtitle: "Figure 4: reference protein coverage (for ref species): 
date: "December 13, 2024"
author: "Adam Freedman"
output: 
  html_document: default
---
  
## Set up
```{r,,message=FALSE, warning=FALSE}
currentdir=getwd()
setwd(currentdir)
library(tidyverse)
``` 

## Data
```{r,,message=FALSE, warning=FALSE}
refprotcov <-read_csv("../../data/RefBlastToPreds.csv")

methodlabels<-c(expression(BRAKER[protein]),expression(BRAKER[RNA]),"BRAKER3",expression(CGP[protein]),expression(CGP[RNA]),expression(Scallop[HISAT2]),expression(Scallop[STAR]),expression(Stringtie[HISAT2]),expression(Stringtie[STAR]),"MAKER","TOGA","Liftoff")

refprotcov <- refprotcov %>% mutate(species = str_replace(species, "dmel", "D. melanogaster")) %>%
     mutate(species = str_replace(species, "dpseudo", "D. pseudoobscura")) %>%  
     mutate(species = str_replace(species, "dyak", "D. yakuba")) %>%
     mutate(species = str_replace(species, "alyrata", "A. lyrata")) %>%
     mutate(species = str_replace(species, "athaliana", "A. thaliana")) %>%
     mutate(species = str_replace(species, "boleracea", "B. oleracea")) %>%
     mutate(species = str_replace(species, "crubella", "C. rubella")) %>%
     mutate(species = str_replace(species, "osativa", "O. sativa")) %>%
     mutate(species = str_replace(species, "sitalica", "S. italica")) %>%
     mutate(species = str_replace(species, "bdistachyon", "B. distachyon")) %>%
     mutate(species = str_replace(species, "zmays", "Z. mays")) %>%
     mutate(species = str_replace(species, "bmori", "B. mori")) %>%
     mutate(species = str_replace(species, "herato", "H. erato")) %>%
     mutate(species = str_replace(species, "dplexippus", "D. plexippus")) %>%
     mutate(species = str_replace(species, "human", "H. sapiens")) %>%
     mutate(species = str_replace(species, "macaque", "M. mulatta")) %>%
     mutate(species = str_replace(species, "dog", "C. familiaris")) %>%
     mutate(species = str_replace(species, "mouse", "M. musculus")) %>%
     mutate(species = str_replace(species, "chicken", "G. gallus")) %>%
     mutate(species = str_replace(species, "quail", "C. japonica")) %>%
     mutate(species = str_replace(species, "mallard", "A. platyrhynchos"))

refprotcov <- refprotcov %>% mutate_at(vars(species),factor,levels=c("D. melanogaster",
              "D. yakuba", "D. pseudoobscura","A. thaliana", "A. lyrata","C. rubella","B. oleracea","Z. mays","S. italica","O. sativa",
               "B. distachyon", "G. gallus","C. japonica","A. platyrhynchos","H. sapiens","M. mulatta","M. musculus","C. familiaris","H. erato","D. plexippus","B. mori"))

refprotcov <- refprotcov %>% mutate_at(vars(method),factor,levels=c("BrkProt","BrkRNA","Braker3","CGPprotein","CGPrnaseq",
    "ScalHisat","ScalStar","StrHisat","StrStar","Maker","TOGA","liftoff"))  %>% mutate(proref_lowcov=proref_blastnomincov-proref_blastcovered0.8)

covlong <-refprotcov %>% select(species,methodtype,group,method,proref_blastcovered0.8,proref_lowcov) %>% pivot_longer(cols=c(proref_blastcovered0.8,proref_lowcov),names_to="covclass",values_to="fracpredprot") %>%
mutate_at(vars(covclass),factor,levels=c("proref_lowcov","proref_blastcovered0.8"))
```

## Figure 4

```{r}
refs_covstackedbar<- covlong %>% filter(species %in% c("D. melanogaster","H. sapiens","Z. mays","A. thaliana","G. gallus")) %>% ggplot(aes(x=method,y=fracpredprot*100,fill=interaction(methodtype,covclass))) +
            geom_bar(width=0.9,stat="identity",position="stack") +
            scale_fill_manual(breaks=c("braker.proref_blastcovered0.8","braker.proref_lowcov","cgp.proref_blastcovered0.8","cgp.proref_lowcov","assembler.proref_blastcovered0.8","assembler.proref_lowcov",
                    "maker.proref_blastcovered0.8", "maker.proref_lowcov",
                     "liftover.proref_blastcovered0.8","liftover.proref_lowcov"),
            values=c("braker.proref_blastcovered0.8"="darkorange3","braker.proref_lowcov"="#FFCDBC",
                     "assembler.proref_blastcovered0.8"="darkorchid3","assembler.proref_lowcov"="#E4C2FF",
                      "cgp.proref_blastcovered0.8"="brown4","cgp.proref_lowcov"="#FF9494",
                      "maker.proref_blastcovered0.8"="black","maker.proref_lowcov"="gray",
                      "liftover.proref_blastcovered0.8"="darkgreen","liftover.proref_lowcov"="#94D994"),labels=c("braker.proref_blastcovered0.8"=expression(paste("BRAKER: ","">=80,"%")),
                      "braker.proref_lowcov"="BRAKER: < 80%","assembler.proref_blastcovered0.8"=expression(paste("assembler: ","">=80,"%")),
                      "assembler.proref_lowcov"="assembler: < 80%","cgp.proref_blastcovered0.8"=expression(paste("CGP: ","">=80,"%")),
                      "cgp.proref_lowcov"="CGP: < 80%", "maker.proref_blastcovered0.8"=expression(paste("MAKER: ","">=80,"%")),
                      "maker.proref_lowcov"="MAKER: < 80%","liftover.proref_blastcovered0.8"=expression(paste("liftover: ","">=80,"%")),
                      "liftover.proref_lowcov"="liftover: < 80%")) +
            theme_classic() +
            theme(axis.text.x=element_text(angle=90, hjust=1,vjust=0.55,size=8,face="plain")) + 
            theme(strip.text = element_text(face="italic")) +
            theme(legend.text.align = 0,legend.text=element_text(size=12),legend.spacing.y = unit(0.1, "cm"),legend.key.size= unit(0.45, "cm")) + 
            guides(fill = guide_legend(byrow = TRUE)) +
            ylab("% predicted proteins") +
            labs(fill = "Reference protein coverage\nby method type") +
            scale_x_discrete(labels=methodlabels) +
            xlab("") +
        

            facet_wrap(~species,ncol=3,nrow=2)
refs_covstackedbar
ggsave(refs_covstackedbar,file="Figure4.pdf",width=8,height=8)   
```
