---
  title: "Genome Annotation Project"
subtitle: "Figure 5: Psauron scores: 
date: "December 13, 2024"
author: "Adam Freedman"
output: 
  html_document: default
---
  
## Set up
```{r,,message=FALSE, warning=FALSE}
currentdir=getwd()
setwd(currentdir)
library(tidyverse)
``` 

## Data
```{r,,message=FALSE, warning=FALSE}
annotations <-read_csv("../../data/Table_S3.csv")
annotations <- annotations %>% filter(!method %in% c("BrkProt-unfilt","BrkProt-fullsupport","BrkRNA-unfilt",
                                                     "BrkRNA-fullsupport","CGPdenovo","TSEBRA","MakerNoRnaNoEvm",
                                                     "MakerRnaEvm","MakerNoRnaEvm")) 

methodlabels<-c("BRAKER2 (P)","BRAKER1 (P)","BRAKER3 (P)",expression(paste(CGP[protein]," (P)")),expression(paste(CGP[RNA]," (P)")),expression(Scallop[HISAT2]),expression(Scallop[STAR]),expression(Stringtie[HISAT2]),expression(Stringtie[STAR]),"MAKER (P)","TOGA (P)","Liftoff")

annotations$method <- factor(annotations$method,levels=c("BrkProt","BrkRNA","Braker3","CGPprotein","CGPrnaseq",
                                           "ScalHisat","ScalStar","StrHisat","StrStar","MakerRnaNoEvm","TOGA","liftoff"))

annotations <- annotations %>% mutate(species = str_replace(species, "dmelanogaster", "D. melanogaster")) %>%
     mutate(species = str_replace(species, "dpseudoobscura", "D. pseudoobscura")) %>%  
     mutate(species = str_replace(species, "dyakuba", "D. yakuba")) %>%
     mutate(species = str_replace(species, "alyrata", "A. lyrata")) %>%
     mutate(species = str_replace(species, "athaliana", "A. thaliana")) %>%
     mutate(species = str_replace(species, "boleracea", "B. oleracea")) %>%
     mutate(species = str_replace(species, "crubella", "C. rubella")) %>%
     mutate(species = str_replace(species, "osativa", "O. sativa")) %>%
     mutate(species = str_replace(species, "sitalica", "S. italica")) %>%
     mutate(species = str_replace(species, "bdistachyon", "B. distachyon")) %>%
     mutate(species = str_replace(species, "zmays", "Z. mays")) %>%
     mutate(species = str_replace(species, "bmori", "B. mori")) %>%
     mutate(species = str_replace(species, "herato", "H. erato")) %>%
     mutate(species = str_replace(species, "dplexippus", "D. plexippus")) %>%
     mutate(species = str_replace(species, "human", "H. sapiens")) %>%
     mutate(species = str_replace(species, "macaque", "M. mulatta")) %>%
     mutate(species = str_replace(species, "dog", "C. familiaris")) %>%
     mutate(species = str_replace(species, "mouse", "M. musculus")) %>%
     mutate(species = str_replace(species, "chicken", "G. gallus")) %>%
     mutate(species = str_replace(species, "quail", "C. japonica")) %>%
     mutate(species = str_replace(species, "mallard", "A. platyrhynchos"))


annotations <- annotations %>% mutate_at(vars(species),factor,levels=c("D. melanogaster",
              "D. yakuba", "D. pseudoobscura","A. thaliana", "A. lyrata","C. rubella","B. oleracea","Z. mays","S. italica","O. sativa",
               "B. distachyon", "G. gallus","C. japonica","A. platyrhynchos","H. sapiens","M. mulatta","M. musculus","C. familiaris","H. erato","D. plexippus","B. mori"))
```




## psauron score dotplot
```{r}
psauron_plot <- annotations %>% filter(group!="heliconines") %>% ggplot(aes(x=species,y=PsauronScore)) + geom_point(aes(fill=method),color="black",pch=21,position = position_jitter(w = 0.33,h = 0),alpha=0.7,size=2.8) +
    scale_fill_manual(labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen")) + 
theme_classic() +
theme(legend.text.align = 0) + 
theme(legend.text=element_text(size=10)) +
theme(axis.text.x=element_text(angle=90, size=10,hjust=1,vjust=0.32,face="italic")) + 
ylab("Psauron score") +
xlab("") + 
geom_vline(xintercept=1.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=2.5,linetype="dotted",size=0.2)+
geom_vline(xintercept=3.5,linetype="solid",size=1) +
geom_vline(xintercept=4.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=5.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=6.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=7.5,linetype="solid",size=1)+
geom_vline(xintercept=8.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=9.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=10.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=11.5,linetype="solid",size=1)+
geom_vline(xintercept=12.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=13.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=14.5,linetype="solid",size=1) +
geom_vline(xintercept=15.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=16.5,linetype="dotted",size=0.2) +
geom_vline(xintercept=17.5,linetype="dotted",size=0.2) +
guides(fill = guide_legend(title = "")) +
theme(legend.position="bottom") +
theme(legend.margin=margin(-22, 0, 0, 0))

print(psauron_plot)

ggsave(psauron_plot,file="Figure5.pdf",width=8,height=5.5)
```

