---
  title: "Genome Annotation Project"
subtitle: "Figure 8: UTR blastp hit freq vs. UTR length ratio (to NCBI): 
date: "December 13, 2024"
author: "Adam Freedman"
output: 
  html_document: default
---
  
## Set up
```{r,,message=FALSE, warning=FALSE}
currentdir=getwd()
setwd(currentdir)
library(tidyverse)
``` 

## Data
```{r,message=FALSE, warning=FALSE}
annotations <-read_csv("../../data/Table_S3.csv")
annotations <- annotations %>% filter(group!="heliconines") %>% filter(method %in% c("ScalHisat","ScalStar","StrHisat","StrStar"))
pred_utrs <- annotations %>% select(species,group,method,PredUtrCdsRatio,NumberCdsWithAnnotatedUtrs,NumberTscriptUtrBlastxHitToSpecies)
genomeQC <-read_csv("../../data/GenomeQcMetrics_2024.11.25.csv")
genome_utr <- genomeQC %>% select(Species,RefMedianUtrCdsRatio) %>%
              dplyr::rename(species=Species)
genome_utr <- genome_utr %>% mutate(species = str_replace(species, "dmelanogaster", "D. melanogaster")) %>%
              mutate(species = str_replace(species, "dpseudoobscura", "D. pseudoobscura")) %>%  
              mutate(species = str_replace(species, "dyakuba", "D. yakuba")) %>%
              mutate(species = str_replace(species, "alyrata", "A. lyrata")) %>%
              mutate(species = str_replace(species, "athaliana", "A. thaliana")) %>%
              mutate(species = str_replace(species, "boleracea", "B. oleracea")) %>%
              mutate(species = str_replace(species, "crubella", "C. rubella")) %>%
              mutate(species = str_replace(species, "osativa", "O. sativa")) %>%
              mutate(species = str_replace(species, "sitalica", "S. italica")) %>%
              mutate(species = str_replace(species, "bdistachyon", "B. distachyon")) %>%
              mutate(species = str_replace(species, "zmays", "Z. mays")) %>%
              mutate(species = str_replace(species, "bmori", "B. mori")) %>%
              mutate(species = str_replace(species, "herato", "H. erato")) %>%
              mutate(species = str_replace(species, "dplexippus", "D. plexippus")) %>%
              mutate(species = str_replace(species, "human", "H. sapiens")) %>%
              mutate(species = str_replace(species, "macaque", "M. mulatta")) %>%
              mutate(species = str_replace(species, "dog", "C. familiaris")) %>%
              mutate(species = str_replace(species, "mouse", "M. musculus")) %>%
              mutate(species = str_replace(species, "chicken", "G. gallus")) %>%
              mutate(species = str_replace(species, "quail", "C. japonica")) %>%
              mutate(species = str_replace(species, "mallard", "A. platyrhynchos"))

data <-left_join(pred_utrs,genome_utr,by = join_by(species))
data <- data %>% mutate_at(vars(species),factor,levels=c("D. melanogaster","D. pseudoobscura",
              "D. yakuba", "A. thaliana", "A. lyrata","B. oleracea","C. rubella","Z. mays","O. sativa","S. italica",
               "B. distachyon", "G. gallus","A. platyrhynchos","C. japonica","H. sapiens","M. mulatta","C. familiaris","M. musculus","B. mori","H. erato","D. plexippus"))

data4sp <- data %>% filter(species %in% c("D. melanogaster","G. gallus","Z. mays","H. sapiens","A. thaliana")) %>%
mutate(PcentTscriptsUtrBlastx=100*NumberTscriptUtrBlastxHitToSpecies/NumberCdsWithAnnotatedUtrs)
```


```{r}
cortest<-cor.test(data4sp$PcentTscriptsUtrBlastx,data4sp$PredUtrCdsRatio/data4sp$RefMedianUtrCdsRatio)
print(cortest)
method_labels <- c(expression(Scallop[HISAT2]),expression(Scallop[STAR]),
    expression(Stringtie[HISAT2]),expression(Stringtie[STAR]))
```

```{r}
utrratio_toblastxfrac_plot <- data4sp %>% ggplot() + 
      geom_point(mapping=aes(y=PcentTscriptsUtrBlastx,x=PredUtrCdsRatio/RefMedianUtrCdsRatio,color=method,shape=species)) +
      xlab("Asssembler UTR-to-CDS ratio/NCBI UTR-to-CDS ratio") +
      ylab("% transcripts with UTR BLASTX hits") +
      scale_color_manual(labels=method_labels,values=c("lightskyblue", "royalblue3","darkorchid3", "magenta")) +
     guides(color = guide_legend(title = "Method",order=1,label.theme = element_text(angle = 0, size=8,face = "plain"))) +
     guides(shape = guide_legend(title = "Species",order=2,label.theme = element_text(angle = 0, size=8,face = "italic"))) +
     theme(legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm"))  +
     theme(text = element_text(size=9)) +
  geom_text(x=1.97,y=35,label=expression(paste("Pearson's ",rho,"=0.68, p=0.0010")),size=2.7)

print(utrratio_toblastxfrac_plot)
ggsave(file="Figure8.tiff",width=5,height=3.5)
```
  