---
  title: "Genome Annotation Project"
subtitle: "Figure S7: proteome vs. transcriptome compleasm scores
date: "December 13, 2024"
author: "Adam Freedman"
output: 
  html_document: default
---
  
## Set up
```{r,,message=FALSE, warning=FALSE}
currentdir=getwd()
setwd(currentdir)
library(tidyverse)
``` 

## Data
```{r,,message=FALSE, warning=FALSE}
annotations <-read_csv("../../data/Table_S3.csv")
annotations <- annotations %>% filter(!method %in% c("BrkProt-unfilt","BrkProt-fullsupport","BrkRNA-unfilt",
                                                     "BrkRNA-fullsupport","CGPdenovo","TSEBRA","MakerNoRnaNoEvm",
                                                     "MakerRnaEvm","MakerNoRnaEvm")) 

methodlabels<-c("BRAKER2 (P)","BRAKER1 (P)","BRAKER3 (P)",expression(paste(CGP[protein]," (P)")),expression(paste(CGP[RNA]," (P)")),expression(Scallop[HISAT2]),expression(Scallop[STAR]),expression(Stringtie[HISAT2]),expression(Stringtie[STAR]),"MAKER (P)","TOGA (P)","Liftoff")

annotations$method <- factor(annotations$method,levels=c("BrkProt","BrkRNA","Braker3","CGPprotein","CGPrnaseq",
                                           "ScalHisat","ScalStar","StrHisat","StrStar","MakerRnaNoEvm","TOGA","liftoff"))

annotations <- annotations %>% mutate(species = str_replace(species, "dmelanogaster", "D. melanogaster")) %>%
     mutate(species = str_replace(species, "dpseudoobscura", "D. pseudoobscura")) %>%  
     mutate(species = str_replace(species, "dyakuba", "D. yakuba")) %>%
     mutate(species = str_replace(species, "alyrata", "A. lyrata")) %>%
     mutate(species = str_replace(species, "athaliana", "A. thaliana")) %>%
     mutate(species = str_replace(species, "boleracea", "B. oleracea")) %>%
     mutate(species = str_replace(species, "crubella", "C. rubella")) %>%
     mutate(species = str_replace(species, "osativa", "O. sativa")) %>%
     mutate(species = str_replace(species, "sitalica", "S. italica")) %>%
     mutate(species = str_replace(species, "bdistachyon", "B. distachyon")) %>%
     mutate(species = str_replace(species, "zmays", "Z. mays")) %>%
     mutate(species = str_replace(species, "bmori", "B. mori")) %>%
     mutate(species = str_replace(species, "herato", "H. erato")) %>%
     mutate(species = str_replace(species, "dplexippus", "D. plexippus")) %>%
     mutate(species = str_replace(species, "human", "H. sapiens")) %>%
     mutate(species = str_replace(species, "macaque", "M. mulatta")) %>%
     mutate(species = str_replace(species, "dog", "C. familiaris")) %>%
     mutate(species = str_replace(species, "mouse", "M. musculus")) %>%
     mutate(species = str_replace(species, "chicken", "G. gallus")) %>%
     mutate(species = str_replace(species, "quail", "C. japonica")) %>%
     mutate(species = str_replace(species, "mallard", "A. platyrhynchos"))


annotations <- annotations %>% mutate_at(vars(species),factor,levels=c("D. melanogaster",
              "D. yakuba", "D. pseudoobscura","A. thaliana", "A. lyrata","C. rubella","B. oleracea","Z. mays","S. italica","O. sativa",
               "B. distachyon", "G. gallus","C. japonica","A. platyrhynchos","H. sapiens","M. mulatta","M. musculus","C. familiaris","H. erato","D. plexippus","B. mori"))
```

## Figure S7: panel A, dipterans
```{r}
dipterans_plot <- annotations %>% filter(group=="dipterans") %>% 
      ggplot() + 
      geom_point(mapping=aes(x=compleasm_transcriptome,y=compleasm_protein,fill=method,shape=species),color="black",alpha=0.75,size=2.2) +
      scale_fill_manual(labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen")) + 
    scale_shape_manual(values=c(21,22,24)) +
    ylab("Proteome compleasm score") +
    xlab("Transcriptome compleasm score") +
    theme_classic() +
    geom_abline(intercept=0,slope=1,lty="dotted",color="black") +
    theme(legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm")) + 
    guides(fill = guide_legend(title = "Method",override.aes = list(shape=21),order=1,label.theme = element_text(angle = 0, size=10,face = "plain"))) +
    guides(shape = guide_legend(title = "Species",order=2,label.theme = element_text(angle = 0, size=8,face = "italic")))
    

print(dipterans_plot)
ggsave(dipterans_plot,file="Figure_S7A.pdf",width=4.5,height=4.5)
```

## Figure S7: panel B, rosids
```{r}
rosids_plot <- annotations %>% filter(group=="rosids") %>% 
      ggplot() + 
      geom_point(mapping=aes(x=compleasm_transcriptome,y=compleasm_protein,fill=method,shape=species),color="black",alpha=0.75,size=2.2) +
      scale_fill_manual(labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen")) + 
     scale_shape_manual(values=c(21,22,24,25)) +
    ylab("Proteome compleasm score") +
    xlab("Transcriptome compleasm score") +
    theme_classic() +
    geom_abline(intercept=0,slope=1,lty="dotted",color="black") +
    theme(legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm")) + 
    guides(fill = guide_legend(title = "Method",override.aes = list(shape=21),order=1,label.theme = element_text(angle = 0, size=10,face = "plain"))) +
    guides(shape = guide_legend(title = "Species",order=2,label.theme = element_text(angle = 0, size=8,face = "italic"))) 
    

print(rosids_plot)
ggsave(rosids_plot,file="Figure_S7B.pdf",width=4.5,height=4.5)
```

## Figure S7: panel C, birds
```{r}
birds_plot <- annotations %>% filter(group=="birds") %>% 
      ggplot() + 
      geom_point(mapping=aes(x=compleasm_transcriptome,y=compleasm_protein,fill=method,shape=species),color="black",alpha=0.75,size=2.2) +
      scale_fill_manual(labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen")) + 
     scale_shape_manual(values=c(21,22,24)) +
    ylab("Proteome compleasm score") +
    xlab("Transcriptome compleasm score") +
    theme_classic() +
    geom_abline(intercept=0,slope=1,lty="dotted",color="black") +
    theme(legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm")) + 
    guides(fill = guide_legend(title = "Method",override.aes = list(shape=21),order=1,label.theme = element_text(angle = 0, size=10,face = "plain"))) +
    guides(shape = guide_legend(title = "Species",order=2,label.theme = element_text(angle = 0, size=8,face = "italic"))) 

print(birds_plot)
ggsave(birds_plot,file="Figure_S7C.pdf",width=4.5,height=4.5)
```

## Figure S7: panel , monocots
```{r}
monocots_plot <- annotations %>% filter(group=="monocots") %>% 
      ggplot() + 
      geom_point(mapping=aes(x=compleasm_transcriptome,y=compleasm_protein,fill=method,shape=species),color="black",alpha=0.75,size=2.2) +
      scale_fill_manual(labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen")) + 
     scale_shape_manual(values=c(21,22,24,25)) +
    ylab("Proteome compleasm score") +
    xlab("Transcriptome compleasm score") +
    theme_classic() +
    geom_abline(intercept=0,slope=1,lty="dotted",color="black") +
    theme(legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm")) + 
    guides(fill = guide_legend(title = "Method",override.aes = list(shape=21),order=1,label.theme = element_text(angle = 0, size=10,face = "plain"))) +
    guides(shape = guide_legend(title = "Species",order=2,label.theme = element_text(angle = 0, size=8,face = "italic"))) 
    

print(monocots_plot)
ggsave(monocots_plot,file="Figure_S7D.pdf",width=4.5,height=4.5)
```

## Figure S7: panel D, mammals
```{r}
mammals_plot <- annotations %>% filter(group=="mammals") %>% 
      ggplot() + 
      geom_point(mapping=aes(x=compleasm_transcriptome,y=compleasm_protein,fill=method,shape=species),color="black",alpha=0.75,size=2.2) +
      scale_fill_manual(labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen")) + 
     scale_shape_manual(values=c(21,22,24,25)) +
    ylab("Proteome compleasm score") +
    xlab("Transcriptome compleasm score") +
    theme_classic() +
    geom_abline(intercept=0,slope=1,lty="dotted",color="black") +
    theme(legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm")) + 
    guides(fill = guide_legend(title = "Method",override.aes = list(shape=21),order=1,label.theme = element_text(angle = 0, size=10,face = "plain"))) +
    guides(shape = guide_legend(title = "Species",order=2,label.theme = element_text(angle = 0, size=8,face = "italic"))) 
    

print(mammals_plot)
ggsave(mammals_plot,file="Figure_S7E.pdf",width=4.5,height=4.5)
```
