---
  title: "Genome Annotation Project"
subtitle: "Figure S3: CDS length violin plots
date: "December 13, 2024"
author: "Adam Freedman"
output: 
  html_document: default
---
  
## Set up
```{r,,message=FALSE, warning=FALSE}
currentdir=getwd()
setwd(currentdir)
library(tidyverse)

methodlabels<-c(expression(BRAKER[protein]),expression(BRAKER[RNA]),"BRAKER3",expression(CGP[protein]),expression(CGP[RNA]),expression(Scallop[HISAT2]),expression(Scallop[STAR]),expression(Stringtie[HISAT2]),expression(Stringtie[STAR]),"MAKER", "TOGA", "Liftoff","NCBI")
```

## Figure S3: panel A, human
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/human_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
human_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(human_lengths_plot) 
ggsave(human_lengths_plot,file="Figure_S3A.pdf",width=6.5,height=2.5)
```

## Figure S3: panel B, dog
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/dog_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
dog_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(dog_lengths_plot) 
ggsave(dog_lengths_plot,file="Figure_S3B.pdf",width=6.5,height=2.5)
```


## Figure S3: panel C, chicken
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/chicken_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
chicken_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(chicken_lengths_plot) 
ggsave(chicken_lengths_plot,file="Figure_S3C.pdf",width=6.5,height=2.5)
```

## Figure S3: panel D, mallard
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/mallard_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
mallard_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(mallard_lengths_plot) 
ggsave(mallard_lengths_plot,file="Figure_S3D.pdf",width=6.5,height=2.5)
```


## Figure S3: panel E, Z. mays
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/zmays_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
zmays_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(zmays_lengths_plot) 
ggsave(zmays_lengths_plot,file="Figure_S3E.pdf",width=6.5,height=2.5)
```


## Figure S3: panel F, O. sativa
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/osativa_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
osativa_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(osativa_lengths_plot) 
ggsave(osativa_lengths_plot,file="Figure_S3F.pdf",width=6.5,height=2.5)
```


## Figure S3: panel G, A. thaliana
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/athaliana_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
athaliana_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(athaliana_lengths_plot) 
ggsave(athaliana_lengths_plot,file="Figure_S3G.pdf",width=6.5,height=2.5)
```

## Figure S3: panel H, C. rubella
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/crubella_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
crubella_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(crubella_lengths_plot) 
ggsave(crubella_lengths_plot,file="Figure_S3H.pdf",width=6.5,height=2.5)
```

## Figure S3: panel I, D. melanogaster
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/dmel_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
dmel_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(dmel_lengths_plot) 
ggsave(dmel_lengths_plot,file="Figure_S3I.pdf",width=6.5,height=2.5)
```


## Figure S3: panel J, D. pseudoobscura
```{r,,message=FALSE, warning=FALSE}
concat_data <-read_table("../../data/cds_length_tables/dpseudo_allmethods_cdslengths.tsv")

concat_data$method <- factor(concat_data$method,levels=c("brkprot","brkrna","braker3","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga","liftoff","ncbi"))

length_medians <- concat_data %>% group_by(method) %>% summarize(median_log10len=median(log10(length)))
dpseudo_lengths_plot<-concat_data %>% ggplot(aes(x=method,y=log10(length),fill=method)) + geom_violin() +
     scale_fill_manual(name="Method",labels=methodlabels,values=c("yellow3","orange","brown4", "red","coral3", "lightskyblue", "royalblue3","darkorchid3", "magenta","gray72","green3","seagreen","white")) +
       ylab(expression(paste(log[10],"CDS length"))) +
       geom_point(data=length_medians,aes(x=method,y=median_log10len),size=1,color="black") +
       xlab("") + 
       theme(axis.title.x=element_blank(),
       axis.text.x=element_blank(),
       axis.ticks.x=element_blank()) +
       guides(fill = guide_legend(title = "")) +
       theme(legend.key.size = unit(0.4, 'cm'), #change legend key size
        legend.key.height = unit(0.4, 'cm'), #change legend key height
        legend.key.width = unit(0.4, 'cm'), #change legend key width
        legend.text = element_text(size=8)) #change legend text font size

print(dpseudo_lengths_plot) 
ggsave(dpseudo_lengths_plot,file="Figure_S3J.pdf",width=6.5,height=2.5)
```



