---
  title: "Genome Annotation Project"
subtitle: "Figure S6: random forest confusion matrix stacked bar"
date: "April 10, 2024"
author: "Adam Freedman"
output: 
  html_document: default
---
  
## Set up
```{r,,message=FALSE, warning=FALSE}
currentdir=getwd()
setwd(currentdir)
library(tidyverse)
``` 

## Data
```{r}
confusion_matrix_data <-read_table("RandomForestErrorRatesMaster.tsv")
confusion_matrix_data <- confusion_matrix_data %>% mutate(genic_class_error=genicFN/(genicFN+genicTP)) %>%
     mutate(intergenic_class_error=intergenicFN/(intergenicFN+intergenicTP)) %>%
     mutate(OOBerror=(genicFN+intergenicFN)/(genicFN+genicTP+intergenicFN+intergenicTP))

confusion_matrix_data <- confusion_matrix_data %>% mutate(species = str_replace(species, "dmel", "D. melanogaster")) %>%
    mutate(species = str_replace(species, "athaliana", "A. thaliana")) %>%
    mutate(species = str_replace(species, "zmays", "Z. mays")) %>%
    mutate(species = str_replace(species, "chicken", "G. gallus")) %>%
    mutate(species = str_replace(species, "human", "H. sapiens"))

confusion_matrix_data$method <- factor(confusion_matrix_data$method,levels=c("brakerprot","brakerrna","cgpprot","cgprna",
                                           "scalhisat","scalstar","stiehisat","stiestar","maker","toga"))

confusion_matrix_data <- confusion_matrix_data %>% mutate(species=factor(species,levels=c("D. melanogaster","G. gallus","H. sapiens","A. thaliana","Z. mays")))

confusion_long_counts <- pivot_longer(confusion_matrix_data, c(genicTP,genicFN,intergenicTP,intergenicFN), names_to="confusion_matrix_class", values_to="classcount") %>% select(species,method,confusion_matrix_class,classcount)
confusion_long_counts <- confusion_long_counts %>% mutate(confusion_matrix_class=factor(confusion_matrix_class,levels=c("intergenicFN","intergenicTP","genicFN","genicTP")))
```

## Figure S6
```{r}
methodlabels<-c(expression(BRAKER[protein]),expression(BRAKER[RNA]),expression(CGP[protein]),expression(CGP[RNA]),expression(Scallop[HISAT2]),expression(Scallop[STAR]),expression(Stringtie[HISAT2]),expression(Stringtie[STAR]),"MAKER","TOGA")
class_labels=c("intergenic: predicted genic", "intergenic: TP","genic: predicted intergenic","genic: TP")
classstack_barplot <- confusion_long_counts %>% 
  ggplot() + geom_bar(aes(x=method,y=classcount,fill=confusion_matrix_class),width=0.7,stat="identity",position="stack",color="black") +
    theme(axis.text.x=element_text(angle=90, hjust=1,vjust=0.3,size=8)) +
    scale_fill_manual(labels=class_labels,values=c("white","dodgerblue","yellow2","darkgreen")) +
    theme(legend.text.align = 0,legend.spacing.y = unit(0.15, "cm"),legend.key.size= unit(0.5, "cm")) +
    ylab("Count") + xlab("") +
    scale_x_discrete(breaks=levels(confusion_long_counts$method),labels=methodlabels) +
    guides(fill = guide_legend(byrow = TRUE)) +
    labs(fill = "Prediction type") +
    facet_wrap(~species) +
    theme(strip.text = element_text(face="italic")) 
print(classstack_barplot)
ggsave(classstack_barplot,file="Figure_S6.pdf",width=7,height=6)
```
